name: node_js CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [16]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Setup npm
      run: npm i -g npm@8.5.x

    - name: Install dependencies
      run: npm ci

    - name: Package lock check
      run: make validate-no-uncommitted-package-lock-changes

    - name: Extract i18n
      run: npm run i18n_extract

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

    - name: Run Coverage
      uses: codecov/codecov-action@v2
